/-
Copyright © 2026, Riley Betts Ltd (rileybetts.ai)
Generated by protoc-gen-lean4-grpc (descriptor path) — do not edit.
Regenerate with: ./scripts/gen-helloworld.sh
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Grpc
import Proto

namespace helloworld

structure HelloRequest where
  name : String := ""
  deriving Inhabited

def HelloRequest.encode (m : HelloRequest) : ByteArray :=
  Id.run do
    let mut acc := ByteArray.empty
    if !m.name.isEmpty then acc := Proto.Wire.encodeString acc 1 m.name
    return acc

def HelloRequest.decode (b : ByteArray) : Except String HelloRequest := do
  let fields ← Proto.Wire.decodeFields (Bytes.Slice.ofByteArray b)
  return {
    name := (Proto.Wire.fieldString? fields 1).getD ""
  }

structure HelloReply where
  message : String := ""
  deriving Inhabited

def HelloReply.encode (m : HelloReply) : ByteArray :=
  Id.run do
    let mut acc := ByteArray.empty
    if !m.message.isEmpty then acc := Proto.Wire.encodeString acc 1 m.message
    return acc

def HelloReply.decode (b : ByteArray) : Except String HelloReply := do
  let fields ← Proto.Wire.decodeFields (Bytes.Slice.ofByteArray b)
  return {
    message := (Proto.Wire.fieldString? fields 1).getD ""
  }

/-- Service `Greeter` client stub (typed). -/
structure GreeterStub where
  channel : Grpc.Channel

namespace GreeterStub

/-- Unary `SayHello`: `HelloRequest` → `HelloReply`. -/
def SayHello (self : GreeterStub) (req : HelloRequest) : IO (Except String HelloReply) := do
  let res ← Grpc.Channel.unary self.channel "helloworld.Greeter" "SayHello" (HelloRequest.encode req)
  if res.status.code != .ok then return .error res.status.message
  return HelloReply.decode res.message

end GreeterStub

/-- Register a typed unary handler for `Greeter/SayHello`. -/
def registerGreeterSayHello (s : Grpc.Server)
    (h : HelloRequest → IO (HelloReply × Grpc.Status)) : Grpc.Server :=
  Grpc.Server.register s "helloworld.Greeter" "SayHello" fun reqBytes => do
    match HelloRequest.decode reqBytes with
    | .error e => return (ByteArray.empty, Grpc.Status.invalidArgument e)
    | .ok req =>
      let (resp, st) ← h req
      return (HelloReply.encode resp, st)

end helloworld
