/-
Copyright (c) 2026 RileyBetts. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
namespace Grpc.Codegen

private def isSpace (c : Char) : Bool :=
  c == ' ' || c == '\t' || c == '\r' || c == '\n'

private def trimChars (cs : List Char) : List Char :=
  cs.dropWhile isSpace |>.reverse.dropWhile isSpace |>.reverse

private def startsWithChars (cs pref : List Char) : Bool :=
  cs.take pref.length == pref

private def endsWithChars (cs suf : List Char) : Bool :=
  cs.drop (cs.length - suf.length) == suf

private def splitOnChars (cs sep : List Char) : List (List Char) :=
  Id.run do
    if sep.isEmpty then return [cs]
    let mut out : List (List Char) := []
    let mut cur : List Char := []
    let mut i := 0
    let arr := cs.toArray
    while i < arr.size do
      if i + sep.length ≤ arr.size &&
          (List.range sep.length).all (fun j => arr[i+j]! == sep[j]!) then
        out := out ++ [cur]
        cur := []
        i := i + sep.length
      else
        cur := cur ++ [arr[i]!]
        i := i + 1
    return out ++ [cur]

private def lines (s : String) : List String :=
  (splitOnChars s.toList ['\n']).map String.ofList

/-- Extract `package X;` -/
def findPackage (text : String) : String :=
  Id.run do
    for line in lines text do
      let t := trimChars line.toList
      if startsWithChars t ("package ".toList) && endsWithChars t [';'] then
        let inner := t.drop ("package ".length) |>.dropLast
        return String.ofList (trimChars inner)
    return ""

structure Rpc where
  name : String
  request : String
  response : String
  clientStreaming : Bool
  serverStreaming : Bool
  deriving Inhabited

structure Service where
  name : String
  rpcs : Array Rpc
  deriving Inhabited

def parseRpc (line : String) : Option Rpc :=
  let t := trimChars line.toList
  if !startsWithChars t ("rpc ".toList) then none
  else
    let rest := t.drop 4
    match splitOnChars rest (") returns (".toList) with
    | [left, right] =>
      match splitOnChars left ['('] with
      | [name, reqPart] =>
        let name := String.ofList (trimChars name)
        let reqPart := trimChars reqPart
        let clientStreaming := startsWithChars reqPart ("stream ".toList)
        let request := String.ofList (trimChars (if clientStreaming then reqPart.drop 7 else reqPart))
        let right := trimChars right
        let right :=
          if endsWithChars right (");".toList) then right.dropLast.dropLast
          else if endsWithChars right [';'] then right.dropLast
          else if endsWithChars right [')'] then right.dropLast
          else right
        let right := trimChars right
        let serverStreaming := startsWithChars right ("stream ".toList)
        let response := String.ofList (trimChars (if serverStreaming then right.drop 7 else right))
        some ⟨name, request, response, clientStreaming, serverStreaming⟩
      | _ => none
    | _ => none

def parseServices (text : String) : Array Service :=
  Id.run do
    let mut services : Array Service := #[]
    let mut current : Option String := none
    let mut rpcs : Array Rpc := #[]
    for line in lines text do
      let t := trimChars line.toList
      if startsWithChars t ("service ".toList) then
        if let some n := current then
          services := services.push ⟨n, rpcs⟩
        rpcs := #[]
        let n := t.drop ("service ".length)
        let n := if endsWithChars n ['{'] then n.dropLast else n
        current := some (String.ofList (trimChars n))
      else if let some rpc := parseRpc (String.ofList t) then
        rpcs := rpcs.push rpc
      else if t == ['}'] then
        if let some n := current then
          services := services.push ⟨n, rpcs⟩
          current := none
          rpcs := #[]
    if let some n := current then
      services := services.push ⟨n, rpcs⟩
    return services

def emitFromProto (text : String) : IO String := do
  let pkg := findPackage text
  let services := parseServices text
  let mut out := "/-\n  Generated by protoc-gen-lean4-grpc — do not edit.\n-/\nimport Grpc\nimport Proto\n\n"
  let ns := String.ofList (pkg.toList.map (fun c => if c == '.' then '_' else c))
  if !pkg.isEmpty then
    out := out ++ s!"namespace {ns}\n\n"
  for svc in services do
    out := out ++ s!"/-- Service `{svc.name}` client stub. -/\n"
    out := out ++ s!"structure {svc.name}Stub where\n  channel : Grpc.Channel\n\n"
    out := out ++ s!"namespace {svc.name}Stub\n\n"
    for rpc in svc.rpcs do
      let full := if pkg.isEmpty then svc.name else pkg ++ "." ++ svc.name
      if !rpc.clientStreaming && !rpc.serverStreaming then
        out := out ++ s!"/-- Unary `{rpc.name}`: request `{rpc.request}` → `{rpc.response}` (payload bytes). -/\n"
        out := out ++ s!"abbrev {rpc.name}Request := ByteArray\n"
        out := out ++ s!"abbrev {rpc.name}Response := ByteArray\n"
        out := out ++ s!"def {rpc.name} (self : {svc.name}Stub) (req : {rpc.name}Request) : IO Grpc.CallResult :=\n"
        out := out ++ s!"  Grpc.Channel.unary self.channel \"{full}\" \"{rpc.name}\" req\n\n"
      else if !rpc.clientStreaming && rpc.serverStreaming then
        out := out ++ s!"/-- Server-streaming `{rpc.name}`. -/\n"
        out := out ++ s!"def {rpc.name} (self : {svc.name}Stub) (req : ByteArray) : IO (Array ByteArray × Grpc.Status) := do\n"
        out := out ++ s!"  let stream ← Grpc.Channel.openStream self.channel \"{full}\" \"{rpc.name}\"\n"
        out := out ++ "  Grpc.Stream.StreamWriter.send stream.writer req\n"
        out := out ++ "  Grpc.Stream.StreamWriter.halfClose stream.writer\n"
        out := out ++ "  let mut out : Array ByteArray := #[]\n"
        out := out ++ "  while true do\n"
        out := out ++ "    match ← Grpc.Stream.StreamReader.recv? stream.reader with\n"
        out := out ++ "    | none => break\n"
        out := out ++ "    | some m => out := out.push m\n"
        out := out ++ "  return (out, Grpc.Status.ok)\n\n"
      else if rpc.clientStreaming && !rpc.serverStreaming then
        out := out ++ s!"/-- Client-streaming `{rpc.name}`. -/\n"
        out := out ++ s!"def {rpc.name} (self : {svc.name}Stub) (reqs : Array ByteArray) : IO Grpc.CallResult := do\n"
        out := out ++ s!"  let stream ← Grpc.Channel.openStream self.channel \"{full}\" \"{rpc.name}\"\n"
        out := out ++ "  for req in reqs do\n"
        out := out ++ "    Grpc.Stream.StreamWriter.send stream.writer req\n"
        out := out ++ "  Grpc.Stream.StreamWriter.halfClose stream.writer\n"
        out := out ++ "  let msg := (← Grpc.Stream.StreamReader.recv? stream.reader).getD ByteArray.empty\n"
        out := out ++ "  return { status := .ok, message := msg, headers := #[], trailers := #[] }\n\n"
      else
        out := out ++ s!"/-- Bidi-streaming `{rpc.name}`. -/\n"
        out := out ++ s!"def {rpc.name} (self : {svc.name}Stub) (reqs : Array ByteArray) : IO (Array ByteArray × Grpc.Status) := do\n"
        out := out ++ s!"  let stream ← Grpc.Channel.openStream self.channel \"{full}\" \"{rpc.name}\"\n"
        out := out ++ "  for req in reqs do\n"
        out := out ++ "    Grpc.Stream.StreamWriter.send stream.writer req\n"
        out := out ++ "  Grpc.Stream.StreamWriter.halfClose stream.writer\n"
        out := out ++ "  let mut out : Array ByteArray := #[]\n"
        out := out ++ "  while true do\n"
        out := out ++ "    match ← Grpc.Stream.StreamReader.recv? stream.reader with\n"
        out := out ++ "    | none => break\n"
        out := out ++ "    | some m => out := out.push m\n"
        out := out ++ "  return (out, Grpc.Status.ok)\n\n"
    out := out ++ s!"end {svc.name}Stub\n\n"
    let full := if pkg.isEmpty then svc.name else pkg ++ "." ++ svc.name
    out := out ++ s!"/-- Register unary handlers for `{svc.name}`. -/\n"
    out := out ++ s!"def register{svc.name} (s : Grpc.Server) (handlers : Array (String × Grpc.UnaryHandler)) : Grpc.Server := Id.run do\n"
    out := out ++ "  let mut s := s\n"
    out := out ++ "  for (method, h) in handlers do\n"
    out := out ++ s!"    s := Grpc.Server.register s \"{full}\" method h\n"
    out := out ++ "  return s\n\n"
    for rpc in svc.rpcs do
      if !rpc.clientStreaming && rpc.serverStreaming then
        out := out ++ s!"def register{rpc.name} (s : Grpc.Server) (h : Grpc.Stream.ServerStreamHandler) : Grpc.Server :=\n"
        out := out ++ s!"  Grpc.Server.registerServerStream s \"{full}\" \"{rpc.name}\" h\n\n"
      else if rpc.clientStreaming && !rpc.serverStreaming then
        out := out ++ s!"def register{rpc.name} (s : Grpc.Server) (h : Grpc.Stream.ClientStreamHandler) : Grpc.Server :=\n"
        out := out ++ s!"  Grpc.Server.registerClientStream s \"{full}\" \"{rpc.name}\" h\n\n"
      else if rpc.clientStreaming && rpc.serverStreaming then
        out := out ++ s!"def register{rpc.name} (s : Grpc.Server) (h : Grpc.Stream.BidiStreamHandler) : Grpc.Server :=\n"
        out := out ++ s!"  Grpc.Server.registerBidi s \"{full}\" \"{rpc.name}\" h\n\n"
  if !pkg.isEmpty then
    out := out ++ "end\n"
  return out

end Grpc.Codegen
