/-
Copyright (c) 2026 RileyBetts. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Grpc.Codegen.Emit
import Bytes.BE
import Bytes.Slice
import Bytes.Pool

/-- Read a length-prefixed protobuf message from stdin (protoc plugin framing). -/
def readPluginRequest : IO ByteArray := do
  let stdin ← IO.getStdin
  let hdr ← stdin.read 4
  if hdr.size < 4 then return ByteArray.empty
  match Bytes.BE.readU32 (Bytes.Slice.ofByteArray hdr) 0 with
  | none => return ByteArray.empty
  | some n =>
    if n == 0 then return ByteArray.empty
    stdin.read n.toUSize

/-- Write length-prefixed protobuf response to stdout. -/
def writePluginResponse (payload : ByteArray) : IO Unit := do
  let stdout ← IO.getStdout
  stdout.write (Bytes.BE.u32Bytes payload.size.toUInt32)
  stdout.write payload

/-- Emit CodeGeneratorResponse-like bytes: file name + content as a minimal hand-rolled message.
    field 15 = file { name = 1, content = 15 } — enough for protoc to write Generated.lean when
    used with our simplified response shape. Prefer LEAN_GRPC_PROTO path for Lake smoke tests. -/
def encodeSimpleResponse (name content : String) : ByteArray :=
  Id.run do
    -- CodeGeneratorResponse.File
    let mut file := ByteArray.empty
    -- name = 1
    let nameBytes := ByteArray.mk (name.toList.map (·.toNat.toUInt8)).toArray
    file := file.push 0x0a -- (1<<3)|2
    file := Bytes.Pool.pushBytes file (encodeVarintLean nameBytes.size)
    file := Bytes.Pool.pushBytes file nameBytes
    -- content = 15
    let contentBytes := ByteArray.mk (content.toList.map (·.toNat.toUInt8)).toArray
    file := file.push 0x7a -- (15<<3)|2
    file := Bytes.Pool.pushBytes file (encodeVarintLean contentBytes.size)
    file := Bytes.Pool.pushBytes file contentBytes
    -- CodeGeneratorResponse.file = 15
    let mut out := ByteArray.empty
    out := out.push 0x7a
    out := Bytes.Pool.pushBytes out (encodeVarintLean file.size)
    out := Bytes.Pool.pushBytes out file
    return out
where
  encodeVarintLean (v : Nat) : ByteArray :=
    Id.run do
      let mut x := v
      let mut out := ByteArray.empty
      while true do
        if x < 0x80 then return out.push x.toUInt8
        out := out.push ((x % 128) + 128).toUInt8
        x := x / 128
      return out

/-- `protoc-gen-lean4-grpc` entry.
    - Args / `LEAN_GRPC_PROTO`: text `.proto` → `LEAN_GRPC_OUT/Generated.lean` (Lake smoke).
    - Else: read CodeGeneratorRequest from stdin (length-prefixed); emit response on stdout. -/
def main (args : List String) : IO UInt32 := do
  let protoPath? ←
    match args with
    | p :: _ => pure (some p)
    | [] => pure (← IO.getEnv "LEAN_GRPC_PROTO")
  match protoPath? with
  | some protoPath =>
    let outDir := (← IO.getEnv "LEAN_GRPC_OUT").getD "."
    let text ← IO.FS.readFile protoPath
    let lean ← Grpc.Codegen.emitFromProto text
    let outPath := System.FilePath.join outDir "Generated.lean"
    IO.FS.writeFile outPath lean
    IO.println s!"wrote {outPath}"
    return 0
  | none =>
    let req ← readPluginRequest
    if req.isEmpty then
      IO.eprintln "usage: protoc-gen-lean4-grpc <file.proto>  (or set LEAN_GRPC_PROTO / run under protoc)"
      return 2
    -- Without full descriptor decode, emit a stub pointing operators at LEAN_GRPC_PROTO mode.
    let lean := "/-\n  Generated by protoc-gen-lean4-grpc (descriptor path).\n  Pass a .proto via LEAN_GRPC_PROTO for full text emit, or grow descriptor decode.\n-/\nimport Grpc\n"
    writePluginResponse (encodeSimpleResponse "Generated.lean" lean)
    return 0
