/-
Copyright © 2026, Riley Betts Ltd (rileybetts.ai)
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Grpc.Codegen.Emit
import Proto.Wire

/-- Read the `CodeGeneratorRequest` from stdin. Per the real `protoc` plugin protocol
    (see `plugin.cc`/`protogen.go`), protoc writes the raw serialized message to the plugin's
    stdin with **no** length-prefix framing and closes the pipe; the plugin just reads until
    EOF. -/
def readPluginRequest : IO ByteArray := do
  (← IO.getStdin).readBinToEnd

/-- Write the raw serialized `CodeGeneratorResponse` to stdout — again no length-prefix
    framing, matching the real protoc plugin protocol. -/
def writePluginResponse (payload : ByteArray) : IO Unit := do
  (← IO.getStdout).write payload

/-- Encode a minimal `CodeGeneratorResponse` with a single generated file
    (`CodeGeneratorResponse.File { name = 1; content = 15 }`, `CodeGeneratorResponse.file = 15`). -/
def encodeSimpleResponse (name content : String) : ByteArray :=
  Id.run do
    let mut file := ByteArray.empty
    file := Proto.Wire.encodeString file 1 name
    file := Proto.Wire.encodeString file 15 content
    Proto.Wire.encodeBytes ByteArray.empty 15 file

/-- `protoc-gen-lean4-grpc` entry.
    - Args / `LEAN_GRPC_PROTO`: text `.proto` → `LEAN_GRPC_OUT/Generated.lean` (Lake smoke; no
      real message-field info available from the lightweight text parser, so RPC I/O types are
      `ByteArray` placeholders).
    - Else: real protoc-plugin path — decode `CodeGeneratorRequest` from stdin (raw, unframed)
      and write a `CodeGeneratorResponse` (raw, unframed) to stdout with real message structs
      and typed client/server signatures. -/
def main (args : List String) : IO UInt32 := do
  let protoPath? ←
    match args with
    | p :: _ => pure (some p)
    | [] => pure (← IO.getEnv "LEAN_GRPC_PROTO")
  match protoPath? with
  | some protoPath =>
    let outDir := (← IO.getEnv "LEAN_GRPC_OUT").getD "."
    let text ← IO.FS.readFile protoPath
    let lean ← Grpc.Codegen.emitFromProto text
    let outPath := System.FilePath.join outDir "Generated.lean"
    IO.FS.writeFile outPath lean
    IO.println s!"wrote {outPath}"
    return 0
  | none =>
    -- Real protoc-plugin invocation: decode the `CodeGeneratorRequest` protoc sent us and emit
    -- real message structs + typed client/server code for every `file_to_generate`. Run via
    -- e.g. `protoc --plugin=protoc-gen-lean4=<this binary> --lean4_out=OUT foo.proto`
    -- (see `scripts/run-codegen-fixture.sh` for a worked example).
    let reqBytes ← readPluginRequest
    if reqBytes.isEmpty then
      IO.eprintln "usage: protoc-gen-lean4-grpc <file.proto>  (or set LEAN_GRPC_PROTO / run under protoc)"
      return 2
    match Grpc.Codegen.CodeGeneratorRequest.decode reqBytes with
    | .error e =>
      writePluginResponse (Grpc.Codegen.encodeErrorResponse s!"protoc-gen-lean4-grpc: decode failed: {e}")
      return 0
    | .ok req =>
      if req.protoFiles.isEmpty || req.fileToGenerate.isEmpty then
        writePluginResponse (encodeSimpleResponse "Generated.lean"
          "/-\n  Generated by protoc-gen-lean4-grpc (descriptor path): empty request.\n-/\nimport Grpc\n")
        return 0
      match Grpc.Codegen.emitFromRequest req with
      | .error e =>
        writePluginResponse (Grpc.Codegen.encodeErrorResponse s!"protoc-gen-lean4-grpc: {e}")
        return 0
      | .ok lean =>
        writePluginResponse (encodeSimpleResponse "Generated.lean" lean)
        return 0
