#!/usr/bin/env bash
# Copyright © 2026, Riley Betts Ltd (rileybetts.ai)
# Regenerate Examples/Helloworld/Generated.lean via the descriptor codegen path
# (same fixture as scripts/run-codegen-fixture.sh — no system protoc required).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
./scripts/run-codegen-fixture.sh >/dev/null

RESP=/tmp/lean-grpc-codegen-fixture-response.bin
OUT="$ROOT/Examples/Helloworld/Generated.lean"

python3 - "$RESP" "$OUT" <<'PY'
import sys

def read_varint(b, i):
    x = s = 0
    while True:
        c = b[i]; i += 1
        x |= (c & 0x7F) << s
        if not (c & 0x80):
            return x, i
        s += 7

def decode_message(buf):
    i = 0
    fields = {}
    while i < len(buf):
        tag, i = read_varint(buf, i)
        field, wt = tag >> 3, tag & 7
        if wt == 0:
            v, i = read_varint(buf, i)
            fields.setdefault(field, []).append(v)
        elif wt == 2:
            ln, i = read_varint(buf, i)
            payload = buf[i : i + ln]
            i += ln
            fields.setdefault(field, []).append(payload)
        else:
            raise SystemExit(f"unsupported wire type {wt}")
    return fields

data = open(sys.argv[1], "rb").read()
top = decode_message(data)
file_msg = decode_message(top[15][0])
content = file_msg[15][0].decode("utf-8")
# Ensure namespace close is explicit for the checked-in module path.
if content.rstrip().endswith("end"):
    content = content.rstrip()[:-3] + "end helloworld\n"
header = """/-
Copyright © 2026, Riley Betts Ltd (rileybetts.ai)
Generated by protoc-gen-lean4-grpc (descriptor path) — do not edit.
Regenerate with: ./scripts/gen-helloworld.sh
Released under Apache 2.0 license as described in the file LICENSE.
-/
"""
# Drop whatever header the emitter wrote and replace with the checked-in banner.
if content.startswith("/-"):
    end = content.find("-/")
    if end >= 0:
        content = content[end + 2 :].lstrip("\n")
open(sys.argv[2], "w").write(header + content)
print(f"wrote {sys.argv[2]}")
PY
